version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels: ["dependencies", "go"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["dependencies", "github-actions"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["dependencies", "docker"]

  - package-ecosystem: "docker"
    directory: "/db/migrations"
    schedule:
      interval: "daily"
    labels: ["dependencies", "docker"]
